# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('company_ref', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('post_box', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Custom extensions to the OSEO standard', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('company_ref', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('post_box', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'invoice addresses',
            },
        ),
        migrations.CreateModel(
            name='OnlineAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('ftp', 'ftp'), ('sftp', 'sftp'), ('ftps', 'ftps')], default='ftp', max_length=20)),
                ('server_address', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('user_password', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('delivery_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oseoserver.DeliveryInformation')),
            ],
            options={
                'verbose_name_plural': 'online addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('InProduction', 'InProduction'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated'), ('Downloaded', 'Downloaded')], default='Submitted', help_text='initial status', max_length=50)),
                ('additional_status_info', models.TextField(blank=True, help_text='Additional information about the status')),
                ('mission_specific_status_info', models.TextField(blank=True, help_text='Additional information about the status that is specific to the mission')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('status_changed_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('remark', models.TextField(blank=True, help_text='Some specific remark about the item')),
                ('order_type', models.CharField(choices=[('PRODUCT_ORDER', 'PRODUCT_ORDER'), ('SUBSCRIPTION_ORDER', 'SUBSCRIPTION_ORDER'), ('MASSIVE_ORDER', 'MASSIVE_ORDER'), ('TASKING_ORDER', 'TASKING_ORDER')], default='PRODUCT_ORDER', max_length=30)),
                ('last_describe_result_access_request', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Some specific reference about this order', max_length=30)),
                ('packaging', models.CharField(blank=True, choices=[('zip', 'zip')], max_length=30)),
                ('priority', models.CharField(blank=True, choices=[('STANDARD', 'STANDARD'), ('FAST_TRACK', 'FAST_TRACK')], max_length=30)),
                ('status_notification', models.CharField(choices=[('None', 'None'), ('Final', 'Final'), ('All', 'All')], default='None', max_length=10)),
                ('extensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='oseoserver.Extension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('InProduction', 'InProduction'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated'), ('Downloaded', 'Downloaded')], default='Submitted', help_text='initial status', max_length=50)),
                ('additional_status_info', models.TextField(blank=True, help_text='Additional information about the status')),
                ('mission_specific_status_info', models.TextField(blank=True, help_text='Additional information about the status that is specific to the mission')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('status_changed_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('remark', models.TextField(blank=True, help_text='Some specific remark about the item')),
                ('collection', models.CharField(choices=[('lst', 'lst'), ('lst10', 'lst10'), ('lst10s', 'lst10s')], max_length=255)),
                ('identifier', models.CharField(blank=True, help_text='identifier for this order item. It is the product Id in the catalog', max_length=255)),
                ('item_id', models.CharField(help_text='Id for the item in the order request', max_length=80)),
                ('url', models.CharField(blank=True, help_text='URL where this item is available', max_length=255)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=False)),
                ('downloads', models.SmallIntegerField(default=0, help_text='Number of times this order item has been downloaded.')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='oseoserver.Extension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrderBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('InProduction', 'InProduction'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated'), ('Downloaded', 'Downloaded')], default='Submitted', help_text='initial status', max_length=50)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oseoserver_productorderbatch_batches', to='oseoserver.Order')),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_batch', to='oseoserver.OrderItem')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='SelectedDeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('mediadelivery', 'mediadelivery'), ('onlinedataaccess', 'onlinedataaccess'), ('onlinedatadelivery', 'onlinedatadelivery')], default='onlinedataaccess', help_text='Type of delivery that has been specified', max_length=30)),
                ('delivery_details', models.CharField(help_text='A comma separated string with further details pertaining the selected delivery type, such as the protocol to use for online data delivery. Each delivery type expects a concrete string format.', max_length=255)),
                ('copies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('value', models.CharField(help_text='Value for this option', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedPaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_payment_option', to='oseoserver.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedSceneSelectionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('value', models.CharField(help_text='Value for this option', max_length=255)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_scene_selection_options', to='oseoserver.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionProcessingBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('InProduction', 'InProduction'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated'), ('Downloaded', 'Downloaded')], default='Submitted', help_text='initial status', max_length=50)),
                ('timeslot', models.DateTimeField()),
                ('collection', models.CharField(choices=[('lst', 'lst'), ('lst10', 'lst10'), ('lst10s', 'lst10s')], max_length=255)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oseoserver_subscriptionprocessingbatch_batches', to='oseoserver.Order')),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_processing_batch', to='oseoserver.OrderItem')),
            ],
            options={
                'verbose_name_plural': 'subscription batches',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSpecificationBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('InProduction', 'InProduction'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated'), ('Downloaded', 'Downloaded')], default='Submitted', help_text='initial status', max_length=50)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oseoserver_subscriptionspecificationbatch_batches', to='oseoserver.Order')),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_specification_batch', to='oseoserver.OrderItem')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_delivery_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='oseoserver.SelectedDeliveryOption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='oseoserver.SelectedOption'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_delivery_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='oseoserver.SelectedDeliveryOption'),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='oseoserver.SelectedOption'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oseoserver_order_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_address', to='oseoserver.Order'),
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_information', to='oseoserver.Order'),
        ),
        migrations.CreateModel(
            name='OrderPendingModeration',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'orders pending moderation',
            },
            bases=('oseoserver.order',),
        ),
    ]
