# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecificationDeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('mediadelivery', 'mediadelivery'), ('onlinedataaccess', 'onlinedataaccess'), ('onlinedatadelivery', 'onlinedatadelivery')], default='onlinedataaccess', help_text='Type of delivery that has been specified', max_length=30)),
                ('delivery_details', models.CharField(help_text='A comma separated string with further details pertaining the selected delivery type, such as the protocol to use for online data delivery. Each delivery type expects a concrete string format.', max_length=255)),
                ('copies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('mediadelivery', 'mediadelivery'), ('onlinedataaccess', 'onlinedataaccess'), ('onlinedatadelivery', 'onlinedatadelivery')], default='onlinedataaccess', help_text='Type of delivery that has been specified', max_length=30)),
                ('delivery_details', models.CharField(help_text='A comma separated string with further details pertaining the selected delivery type, such as the protocol to use for online data delivery. Each delivery type expects a concrete string format.', max_length=255)),
                ('copies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annotation', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_delivery_option', to='oseoserver.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='selecteddeliveryoption',
            name='order',
        ),
        migrations.RemoveField(
            model_name='itemspecification',
            name='selected_delivery_option',
        ),
        migrations.DeleteModel(
            name='SelectedDeliveryOption',
        ),
        migrations.AddField(
            model_name='itemspecificationdeliveryoption',
            name='item_specification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_delivery_option', to='oseoserver.ItemSpecification'),
        ),
    ]
