# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0003_auto_20170125_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorderbatch',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='subscriptionprocessingbatch',
            name='order_items',
        ),
        migrations.RemoveField(
            model_name='subscriptionspecificationbatch',
            name='order_items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_order_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oseoserver.ProductOrderBatch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subscription_processing_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oseoserver.SubscriptionProcessingBatch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subscription_specification_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oseoserver.SubscriptionSpecificationBatch'),
        ),
    ]
