# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0004_auto_20170125_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(blank=True, choices=[('STANDARD', 'STANDARD'), ('FAST_TRACK', 'FAST_TRACK')], default='STANDARD', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='collection',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_order_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='oseoserver.ProductOrderBatch'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subscription_processing_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='oseoserver.SubscriptionProcessingBatch'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subscription_specification_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='oseoserver.SubscriptionSpecificationBatch'),
        ),
        migrations.AlterField(
            model_name='selecteddeliveryoption',
            name='delivery_type',
            field=models.CharField(choices=[('MEDIA_DELIVERY', 'MEDIA_DELIVERY'), ('ONLINE_DATA_DELIVERY', 'ONLINE_DATA_DELIVERY'), ('ONLINE_DATA_ACCESS', 'ONLINE_DATA_ACCESS')], default='onlinedataaccess', help_text='Type of delivery that has been specified', max_length=30),
        ),
    ]
