# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0005_auto_20170130_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('InProduction', 'InProduction'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated'), ('Downloaded', 'Downloaded')], default='Submitted', help_text='processing status', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, help_text='Some specific remark about the item')),
                ('collection', models.CharField(max_length=255)),
                ('identifier', models.CharField(blank=True, help_text='identifier for the order item. It is the product Id in the catalogue.', max_length=255)),
                ('item_id', models.CharField(help_text='Id for the item in the order request', max_length=80)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_specifications', to='oseoserver.Extension')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedItemOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('value', models.CharField(help_text='Value for this option', max_length=255)),
                ('item_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='oseoserver.ItemSpecification')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedOrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('value', models.CharField(help_text='Value for this option', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productorderbatch',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subscriptionprocessingbatch',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subscriptionspecificationbatch',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_order_batch',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_delivery_option',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subscription_processing_batch',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subscription_specification_batch',
        ),
        migrations.RemoveField(
            model_name='selectedpaymentoption',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='selectedsceneselectionoption',
            name='order_item',
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_information', to='oseoserver.Order'),
        ),
        migrations.AlterField(
            model_name='invoiceaddress',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_address', to='oseoserver.Order'),
        ),
        migrations.AlterField(
            model_name='onlineaddress',
            name='delivery_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_addresses', to='oseoserver.DeliveryInformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='oseoserver.Extension'),
        ),
        migrations.AlterField(
            model_name='selecteddeliveryoption',
            name='delivery_type',
            field=models.CharField(choices=[('mediadelivery', 'mediadelivery'), ('onlinedataaccess', 'onlinedataaccess'), ('onlinedatadelivery', 'onlinedatadelivery')], default='onlinedataaccess', help_text='Type of delivery that has been specified', max_length=30),
        ),
        migrations.DeleteModel(
            name='ProductOrderBatch',
        ),
        migrations.DeleteModel(
            name='SelectedOption',
        ),
        migrations.DeleteModel(
            name='SubscriptionProcessingBatch',
        ),
        migrations.DeleteModel(
            name='SubscriptionSpecificationBatch',
        ),
        migrations.AddField(
            model_name='selectedorderoption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='oseoserver.Order'),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_specifications', to='oseoserver.Order'),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='selected_delivery_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_specification', to='oseoserver.SelectedDeliveryOption'),
        ),
        migrations.AddField(
            model_name='batch',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='oseoserver.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='oseoserver.Batch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='oseoserver.ItemSpecification'),
        ),
        migrations.AddField(
            model_name='selectedpaymentoption',
            name='item_specification',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selected_payment_option', to='oseoserver.ItemSpecification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedsceneselectionoption',
            name='item_specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selected_scene_selection_options', to='oseoserver.ItemSpecification'),
            preserve_default=False,
        ),
    ]
