# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0007_auto_20170213_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_delivery_option',
        ),
        migrations.AddField(
            model_name='selecteddeliveryoption',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_delivery_option', to='oseoserver.Order'),
        ),
    ]
