# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0051_auto_20150515_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oseouser',
            name='oseo_group',
        ),
        migrations.RemoveField(
            model_name='oseouser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='authorized_groups',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OseoGroup',
        ),
        migrations.DeleteModel(
            name='OseoUser',
        ),
    ]
