# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0052_auto_20160524_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfiguration',
            name='delivery_options',
            field=models.ManyToManyField(blank=True, to='oseoserver.DeliveryOption'),
        ),
        migrations.AlterField(
            model_name='orderconfiguration',
            name='options',
            field=models.ManyToManyField(blank=True, to='oseoserver.Option'),
        ),
        migrations.AlterField(
            model_name='orderconfiguration',
            name='payment_options',
            field=models.ManyToManyField(blank=True, to='oseoserver.PaymentOption'),
        ),
        migrations.AlterField(
            model_name='orderconfiguration',
            name='scene_selection_options',
            field=models.ManyToManyField(blank=True, to='oseoserver.SceneSelectionOption'),
        ),
    ]
