# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0053_auto_20160524_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertype',
            name='item_processor',
        ),
        migrations.AlterField(
            model_name='customizableitem',
            name='status',
            field=models.CharField(choices=[(b'Accepted', b'Accepted'), (b'Cancelled', b'Cancelled'), (b'Completed', b'Completed'), (b'Downloaded', b'Downloaded'), (b'Failed', b'Failed'), (b'InProduction', b'InProduction'), (b'Submitted', b'Submitted'), (b'Suspended', b'Suspended'), (b'Terminated', b'Terminated')], default=b'Submitted', help_text=b'initial status', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[(b'MASSIVE_ORDER', b'MASSIVE_ORDER'), (b'PRODUCT_ORDER', b'PRODUCT_ORDER'), (b'SUBSCRIPTION_ORDER', b'SUBSCRIPTION_ORDER'), (b'TASKING_ORDER', b'TASKING_ORDER')], default=b'PRODUCT_ORDER', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(blank=True, choices=[(b'FAST_TRACK', b'FAST_TRACK'), (b'STANDARD', b'STANDARD')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_notification',
            field=models.CharField(choices=[(b'All', b'All'), (b'Final', b'Final'), (b'None', b'None')], default=b'None', max_length=10),
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
