# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0054_auto_20160524_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='collection',
            field=models.CharField(choices=[(b'', b'')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionbatch',
            name='collection',
            field=models.CharField(choices=[(b'', b'')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='MassiveOrderConfiguration',
        ),
        migrations.DeleteModel(
            name='OrderConfiguration',
        ),
        migrations.DeleteModel(
            name='ProductOrderConfiguration',
        ),
        migrations.DeleteModel(
            name='SubscriptionOrderConfiguration',
        ),
        migrations.DeleteModel(
            name='TaskingOrderConfiguration',
        ),
    ]
