# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0055_auto_20160524_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='collection',
            field=models.CharField(choices=[(b'dummy collection', b'dummy collection')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionbatch',
            name='collection',
            field=models.CharField(choices=[(b'dummy collection', b'dummy collection')], max_length=255),
        ),
    ]
