# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0056_auto_20160530_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediadelivery',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='mediadelivery',
            name='deliveryoption_ptr',
        ),
        migrations.RemoveField(
            model_name='onlinedataaccess',
            name='deliveryoption_ptr',
        ),
        migrations.RemoveField(
            model_name='onlinedatadelivery',
            name='deliveryoption_ptr',
        ),
        migrations.RemoveField(
            model_name='optionchoice',
            name='option',
        ),
        migrations.RemoveField(
            model_name='sceneselectionoptionchoice',
            name='scene_selection_option',
        ),
        migrations.RemoveField(
            model_name='selecteddeliveryoption',
            name='option',
        ),
        migrations.AddField(
            model_name='selecteddeliveryoption',
            name='delivery_details',
            field=models.CharField(default='dummy', help_text=b'A comma separated string with further details pertaining the selected delivery type, such as the protocol to use for online data delivery. Each delivery type expects a concrete string format.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selecteddeliveryoption',
            name='delivery_type',
            field=models.CharField(choices=[(b'mediadelivery', b'mediadelivery'), (b'onlinedataaccess', b'onlinedataaccess'), (b'onlinedatadelivery', b'onlinedatadelivery')], default=b'onlinedataaccess', help_text=b'Type of delivery that has been specified', max_length=30),
        ),
        migrations.AlterField(
            model_name='selectedoption',
            name='option',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedpaymentoption',
            name='option',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedsceneselectionoption',
            name='option',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='DeliveryOption',
        ),
        migrations.DeleteModel(
            name='MediaDelivery',
        ),
        migrations.DeleteModel(
            name='OnlineDataAccess',
        ),
        migrations.DeleteModel(
            name='OnlineDataDelivery',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionChoice',
        ),
        migrations.DeleteModel(
            name='PaymentOption',
        ),
        migrations.DeleteModel(
            name='SceneSelectionOption',
        ),
        migrations.DeleteModel(
            name='SceneSelectionOptionChoice',
        ),
    ]
