# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0058_auto_20160605_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oseofile',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='downloads',
            field=models.SmallIntegerField(default=0, help_text=b'Number of times this order item has been downloaded.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='url',
            field=models.CharField(blank=True, help_text=b'URL where this item is available', max_length=255),
        ),
        migrations.DeleteModel(
            name='OseoFile',
        ),
    ]
