# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oseoserver', '0059_auto_20160616_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[(b'Accepted', b'Accepted'), (b'Cancelled', b'Cancelled'), (b'Completed', b'Completed'), (b'Downloaded', b'Downloaded'), (b'Failed', b'Failed'), (b'InProduction', b'InProduction'), (b'Submitted', b'Submitted'), (b'Suspended', b'Suspended'), (b'Terminated', b'Terminated')], default=b'Submitted', help_text=b'initial status', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='collection',
            field=models.CharField(choices=[(b'dummy_collection', b'dummy_collection'), (b'lst', b'lst')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionbatch',
            name='collection',
            field=models.CharField(choices=[(b'dummy_collection', b'dummy_collection'), (b'lst', b'lst')], max_length=255),
        ),
    ]
